### ISSUE TITLE
[Feature Request] Use jsonc for config file

### ISSUE THREAD

**Issue by lonix1** [JeremyFunk/hidefiles#10]
The `hide-files.json` config file is expected to be json, which means no comments. If I add documentation to that file, the extension breaks.

Please allow `jsonc` as well - vscode supports it.

**Comment by JeremyFunk** [comment]
This would require quite an extensive rework and I currently have too little time to implement it. 
You can use the description and details tag to create comments on profiles. These two fields are only in Hide Files for backwards compatability to pre-2.0.0 versions. Could look something like this:
![image](https://user-images.githubusercontent.com/29690247/165639359-91401f5c-bd48-4d47-9272-112e5f5a001a.png).

I will keep this issue open, I eventaully want to implement this but probably not until summer vacation.

**Comment by lonix1** [comment]
That's a nice workaround, thanks!
