### ISSUE TITLE
Would have been perfect if it worked!

### ISSUE THREAD

**Issue by feedyourmind** [JeremyFunk/hidefiles#4]
Hi, 

I was so excited to start using this, but unfortunately it doesn't work. 
First of all, i recommend  you update the description of the extension in the marketplace to include the reply you gave here: 
https://github.com/JeremyFunk/hidefiles/issues/3#issuecomment-963398284 
It wasn't obvious to me how it's supposed to work before reading that. 

The real problem is that when i try >HideFiles : Reload Configuration  ,nothing happens. there is no feedback or error message. it does not prompt me to which profile i want. simply nothing. 
I have tried simple profile definition from the sample and even tried reducing it to single profile with single element array for 'hidden'. 
I tried to check the Output>Log (extension host) and Log (Window) , but could not find something that would help me understand why it's not working. 

I am running Visual Studio Code on a mac. 
Specifics:
Version: 1.62.3 (Universal)
Commit: ccbaa2d27e38e5afa3e5c21c1c7bef4657064247
Date: 2021-11-17T07:59:13.865Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin arm64 21.1.0

**Comment by feedyourmind** [comment]
Update: I decided to take a closer look so i debugged it and i made it work. 
Turns out the issue is at https://github.com/JeremyFunk/hidefiles/blob/e67899493d13debc5a410f960ae44e48dabf8dbe/src/config.ts#L33
        const path = `${folders[0].uri.fsPath}\\hide-files.json`
On Mac, this does not work. 
Changing the line to: 
        const path = `${folders[0].uri.fsPath}/hide-files.json`
fixed it and everything else worked as expected. 
Could you please update your code to make the paths work for all platforms?
i suggest you use 
  const path = path.join(`${folders[0].uri.fsPath}`,`hide-files.json`)

 Thank you and great work on the plugin, i really like the concept

**Comment by JeremyFunk** [comment]
Hi, 
I am sorry to hear that my extension didn't work for you. I have no access to a Mac, so I could not debug on MacOS but that was a pretty dense oversight from me, thanks for pointing it out! 
As soon as I find some time I will fix it, rework the code, add proper feedback to the user, rewrite the README and test it on Linux and Windows. 
I will leave a comment here as soon as a new version is available!

Could you test it on MacOS when the new version is released? That would be awesome!

**Comment by feedyourmind** [comment]
That's great thank you. 
I already patched it locally with the fix i suggested and i now use it in my projects. 
Once you release the update, i'll pull the official extension. 
sure, i'll check it in the macbook and give you feedback that would benefit others as well.
