### ISSUE TITLE
Allow to inform witch VSCode settings to save file exclusion config: workspace or user

### ISSUE THREAD

**Issue by erickponce** [JeremyFunk/hidefiles#7]
Hi there! 👋

I think it would be nice to be able to inform witch VSCode settings to save file exclusion config:
**workspace** or **user**

It would be useful to me, because I don't want to *commit* the resulting VSCode settings on repo. 

Maybe something like this in `hide-files.json`:
```
{
"vscodeSettings": "user", #workspace (default) or user
"profiles": [...]
}
```

Another config that are maybe interesting to have, is something like:
```"defaultProfile": "my-profile"```
But it would probably require complex bootstrap logic.

Thanks for the extension! 🚀

**Comment by JeremyFunk** [comment]
Hi, I like the idea, I hope I find time to add it in the coming days.
I just published a major rework of the extension and would love to hear your feedback on the new version. Let me know what you think and any additional ideas/features you'd like to see.

**Comment by JeremyFunk** [comment]
See #9
