### ISSUE TITLE
[Feature Request] Move config file to .vscode

### ISSUE THREAD

**Issue by lonix1** [JeremyFunk/hidefiles#9]
Nice extension, thanks for making it!

Would be nice to be able to move config file to `.vscode/hide-files.json`. That is where it belongs, rather than the workspace root.

**Comment by JeremyFunk** [comment]
I have just published V2.1.0. When you have set up a local configuration it will automatically move it to your workspace settings (.vscode/settings.json). It is no longer possible to use root level hide-files.json configuration.

**Comment by lonix1** [comment]
Excellent update, thanks.

**Comment by riolly** [comment]
It becomes problematic if the repo also includes the `.vscode` folder in to git history.
Every time toggle the hide files, git will detect changes.
